"""User roles and agency subscription states for multi-tenant onboarding."""

USER_ROLE_PLATFORM_SUPER_ADMIN = "platform_super_admin"
USER_ROLE_TENANT_SUPER_USER = "tenant_super_user"
USER_ROLE_TENANT_AGENT = "tenant_agent"

USER_ROLES = (
    USER_ROLE_PLATFORM_SUPER_ADMIN,
    USER_ROLE_TENANT_SUPER_USER,
    USER_ROLE_TENANT_AGENT,
)

SUBSCRIPTION_STATE_ACTIVE = "Active"
SUBSCRIPTION_STATE_TRIALING = "Trialing"
SUBSCRIPTION_STATE_PAST_DUE = "Past Due"
SUBSCRIPTION_STATE_LOCKED = "Locked"

SUBSCRIPTION_STATES = (
    SUBSCRIPTION_STATE_ACTIVE,
    SUBSCRIPTION_STATE_TRIALING,
    SUBSCRIPTION_STATE_PAST_DUE,
    SUBSCRIPTION_STATE_LOCKED,
)

DEFAULT_INVITATION_ROLE = USER_ROLE_TENANT_AGENT
